version: "3"

networks:
  network-front:
    driver: bridge
  network-back:
    driver: bridge

volumes:
  db-data:

services:
  db-backend:
    build: .
    container_name: db-backend
    depends_on:
    - "postgre-db"
    ports:
    - "8080:8080"
    networks:
    - network-front
    - network-back
  postgre-db:
    image: postgres:9.5
    container_name: postgre-db
    expose:
    - "5432"
    volumes:
    - "db-data:/var/lib/postgresql/data"
    networks:
    - network-back
    environment:
      POSTGRES_DB: springbootdb